# @name sign-up-user
POST http://localhost:3333/sign-up
Content-Type: application/json

{
    "name": "John Doe",
    "email": "johndoe5@example.com",
    "password": "Aasd123@"
}

###

# @name authenticate-user
POST http://localhost:3333/authenticate-user
Content-Type: application/json

{
    "email": "johndoe@example.com",
    "password": "Aasd123@"
}

###

# @name add-money
POST http://localhost:3333/add-money
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjFkNTNmMmU4MmFmYzIxNmI3ZmQ4OTUiLCJpYXQiOjE3MTMzMTAyNjQsImV4cCI6MTcxMzM5NjY2NH0.wssUVi066MNSxnxoN2l_AuOLR5N5vo0ttng71ORpWbs

{
    "value": 500000
}

###

# @name get-balance
GET http://localhost:3333/balance
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjFkNTNmMmU4MmFmYzIxNmI3ZmQ4OTUiLCJpYXQiOjE3MTMzMTAyNjQsImV4cCI6MTcxMzM5NjY2NH0.wssUVi066MNSxnxoN2l_AuOLR5N5vo0ttng71ORpWbs

###

# @name buy-ticket
POST http://localhost:3333/tickets
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjFkNTNmMmU4MmFmYzIxNmI3ZmQ4OTUiLCJpYXQiOjE3MTMzMTAyNjQsImV4cCI6MTcxMzM5NjY2NH0.wssUVi066MNSxnxoN2l_AuOLR5N5vo0ttng71ORpWbs

{
    "numbers": [1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1]
}

###

# @name list-active-tickets
GET http://localhost:3333/tickets
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjFkNTNmMmU4MmFmYzIxNmI3ZmQ4OTUiLCJpYXQiOjE3MTMzMTAyNjQsImV4cCI6MTcxMzM5NjY2NH0.wssUVi066MNSxnxoN2l_AuOLR5N5vo0ttng71ORpWbs

###

# @name count-active-tickets
GET http://localhost:3333/tickets/count
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjFkNTNmMmU4MmFmYzIxNmI3ZmQ4OTUiLCJpYXQiOjE3MTMzMTAyNjQsImV4cCI6MTcxMzM5NjY2NH0.wssUVi066MNSxnxoN2l_AuOLR5N5vo0ttng71ORpWbs

###

# @name sort-bet
POST http://localhost:3333/bets
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjFkNTNmMmU4MmFmYzIxNmI3ZmQ4OTUiLCJpYXQiOjE3MTMzMTAyNjQsImV4cCI6MTcxMzM5NjY2NH0.wssUVi066MNSxnxoN2l_AuOLR5N5vo0ttng71ORpWbs

{
}


###

# @name list-bets
GET http://localhost:3333/bets?page=1&size=20
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjFkNTNmMmU4MmFmYzIxNmI3ZmQ4OTUiLCJpYXQiOjE3MTMzMTAyNjQsImV4cCI6MTcxMzM5NjY2NH0.wssUVi066MNSxnxoN2l_AuOLR5N5vo0ttng71ORpWbs

###

# @name get-profit
GET http://localhost:3333/profit
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjFkNTNmMmU4MmFmYzIxNmI3ZmQ4OTUiLCJpYXQiOjE3MTMzMTAyNjQsImV4cCI6MTcxMzM5NjY2NH0.wssUVi066MNSxnxoN2l_AuOLR5N5vo0ttng71ORpWbs

###

# @name get-tickets-costs
GET http://localhost:3333/config/tickets-costs

###

# @name get-tickets-costs
GET http://localhost:3333/config/bets-rewards