# @name sign-up-user
POST http://localhost:3333/sign-up
Content-Type: application/json

{
    "name": "John Doe",
    "email": "johndoe5@example.com",
    "password": "Aasd123@"
}

###

# @name authenticate-user
POST http://localhost:3333/authenticate-user
Content-Type: application/json

{
    "email": "johndoe@example.com",
    "password": "Aasd123@"
}

###

# @name buy-ticket
POST http://localhost:3333/buy-ticket
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjFkNTNmMmU4MmFmYzIxNmI3ZmQ4OTUiLCJpYXQiOjE3MTMyMjMxNTEsImV4cCI6MTcxMzMwOTU1MX0.WSD-8akhUYEkDCSSkhyBgl63YdIZdhK857OIXOAyIMY

{
    "userId": "661d53f2e82afc216b7fd895",
    "numbers": [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
}